# Generated by Django 4.2.7 on 2026-09-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
    ]
